### ISSUE TITLE
iosxr_interface | bundle-ether and ipv6_link_local_address

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#129]
Hello,

It is possible to create Bundle-Ether interfaces, but it is not possible to configure a physical interface to be a part of a channel-group. Is there a reason for this?

Also, when trying to configure an interface for the first time, ipv6_link_local_address is required, but can be deleted after it's been created first. It's not listed as a requirement, and if you do not specify a ipv6_link_local_address it throws a lot of random errors that have no correlation to the fact that ipv6_link_local_address is missing.

Does this really have to be specified though? Seems like it shouldn't be necessary.

Great work on the new updates you've made lately, it's made working with this provider great! 

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/d6639c1eebe30eef7ab5d6ac03cd83ecab907aa2

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/445e016181dc6938ced795481d9f1a447641e556

**Comment by danischm** [comment]
Fixed in v0.2.1 .
