### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#140]
Hello,

First of all, I'd like to thank you for all the work you have done on this provider. It works great, and especially in the last month or so, it has improved a lot. Its awesome!

I am in the process of rewriting a whole router config using terraform, and therefore I am posting these features that I see as missing.

 - Ability to configure NTP
 -  Ability to configure bfd
 - Ability to configure and setup flow, export, sampler maps and monitors.

Would be nice to see these added as well in the future.

Thank you and best wishes,
rjoensen

**Comment by danischm** [comment]
If you could share the relevant CLI snippets we can look into it. Be aware that you can also use the generic `iosxr_gnmi` resource to manage any configuration where we do not have a dedicated resource yet. The easiest way to work with `iosxr_gnmi` is by configuring the respective config via CLI first, then display the modelled config using `sh run ... | json unified-model` and use it to derive the `iosxr_gnmi` config from it.

**Comment by rjoensen** [comment]
Hello,

NTP example in the cli config looks like this;

ntp
 server <snipped>
 server <snipped>
 server ipv6 <snipped> prefer
 server ipv6 <snipped>
 access-group ipv4 peer NTP-PEER-V4
 source Loopback0
 update-calendar
!

BFD example in the cli config looks like this;

bfd
 interface <snipped>
  echo ipv4 source <snipped>
 !
 multipath include location 0/0/CPU0
 echo disable
!

flow export/monitor/sampler examples;

flow exporter-map <name>
 version v9
  options interface-table timeout 300
  options vrf-table timeout 300
  options sampler-table timeout 300
 !
 transport udp <udp-port>
 source Loopback0
 destination <destination-ip>
!
flow monitor-map <name>
 record ipv4
 exporter <name>
 cache entries 16384
 cache timeout active 60
 cache timeout inactive 30
!
flow monitor-map <name>
 record ipv6
 exporter <name>
 cache entries 16384
 cache timeout active 60
 cache timeout inactive 30
!
sampler-map 1-of-1
 random 1 out-of 1
!

note, this also requires "flow ipv4/ipv6 monitor" abilities in iosxr_interface resource to be able to apply to interfaces.

I’ll take a look at iosxr_gnmi and see what I can get working for now. Thanks for the recommendation, and thank you for your help.

Best wishes,
rjoensen

**Comment by rjoensen** [comment]
Accidentally closed this issue. reopening.

**Comment by danischm** [comment]
Could you please add the related CLI config snippets? Thanks.

**Comment by danischm** [comment]
All of this should be included in the v0.2.3 release. I could not test the flow resources due to missing support on XRv. If anything is not working as expected, please re-open this issue.
