### ISSUE TITLE
iosxr_router_bgp

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#142]
Hello,

timers_minimum_acceptable_holdtime does not exist.

      "timers": {
       "bgp": {
        "keepalive-interval": 30, << exists
        "holdtime": 90, << exits
        "minimum-acceptable-holdtime": 60 << missing

bgp_bestpath does not exist (e.g. to set bgp bestpath compare-routerid)

Would be nice to have this added to the resource as well.

./Ragnar

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/b6e0fac6909c08409f8a0f7f378d771f768ac5f7

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/28ac2678b705b8947f592b032e2bc2634a44ce45

**Comment by danischm** [comment]
added in v0.2.3
