### ISSUE TITLE
iosxr_ntp

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#152]
Hello,

While working with ipv6_peers_servers is there a reason why address AND ipv6_address are required? For it to configure correctly, I had to specify both, using the same peer address, but it applies the config correctly.

Maybe this is a bug?

Best wishes,
rjoensen

**Comment by danischm** [comment]
It is a yang model quirk.

**Comment by danischm** [comment]
Addressed in v0.2.4 .
