### ISSUE TITLE
iosxr_flow_monitor_map

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#153]
Hello,

iosxr_flow_monitor_map seems to be missing the ability to simply configure "record ipv4"

RP/0/RP0/CPU0:<snipped>(config-fmm)#record ipv4 ?   
  gtp      IPV4 gtp record format
  peer-as  Record peer AS
  <cr>     
RP/0/RP0/CPU0:<snipped>(config-fmm)#record ipv4 

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/eab00b8b3589f8d2825654e8cf1d5b76f4773110

**Comment by danischm** [comment]
Addressed in v0.2.4 .
