### ISSUE TITLE
iosxr_router_isis

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#154]
Hello,

Is there a reason for set_overload_bit_levels that you have to set level_id? This is not necessary in the ios-xr config.

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/2fd12764b8f19bbeccec98a5fdd41afeb30c2d2e

**Comment by danischm** [comment]
Addressed in v0.2.4 .
