### ISSUE TITLE
iosxr_router_isis_interface / iosxr_router_isis_interface_address_family

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#155]
Hello,

iosxr_router_isis_interface / iosxr_router_isis_interface_address_family is missing the ability to set metrics for address family v6/v4 unicast.

E.g.

 interface <snipped>
  point-to-point
  address-family ipv4 unicast
   metric 500 level 2
  !
  address-family ipv6 unicast
   metric 500 level 2
  !

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/17981497ccd5824a46aab80e890c129ad5fe751e

**Comment by danischm** [comment]
Addressed in v0.2.4 .
