### ISSUE TITLE
iosxr_router_bgp

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#156]
Hello,

I seem to be able to set next hop trigger delays, seems to be missing as a feature. Example;

router bgp <snipped>
 bgp router-id <snipped>
 bgp bestpath compare-routerid
 address-family ipv4 unicast
  maximum-paths ibgp <number>
  nexthop trigger-delay critical <seconds>
  nexthop trigger-delay non-critical <seconds>

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/fc1dafb721f39de14f1e232099764fc3a27a7d9b
