### ISSUE TITLE
iosxr_router_bgp_neighbor_group

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#157]
Hello,

iosxr_router_bgp_neighbor_group is missing the ability to use "advertisement-interval" for neighbor-groups.

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/9725c736ea981df2940f8420a99a45e6ef032579

**Comment by danischm** [comment]
Addressed in v0.2.4 .
