### ISSUE TITLE
iosxr_l2vpn

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#158]
Hello,

iosxr_l2vpn does not appear to be complete. I am trying to use it to configure this;

Don't seem to be able to setup load-balancing nor configure pw-class.

Best wishes,
rjoensen

**Comment by rjoensen** [comment]
Attaching an example;

pw-class <name>
 encapsulation mpls
  transport-mode plan passthrough | ethernet | vlan
  load-balancing
  pw-label
 flow-label both

**Comment by rjoensen** [comment]
And under the l2vpn configuration load-balancing also needs to be configured as flow and then you have multiple options, e.g. src-dst-ip, etc.

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/634511ea906ad4a9c3956a20cef0fd72ed402381

**Comment by rjoensen** [comment]
Hello,

I just got around to actually test this and it appears I was not very clear when reporting this. I believe what's missing is jut the pw-class ability.

l2vpn
 load-balancing flow src-dst-ip
 pw-class <class-name>
  encapsulation mpls
   transport-mode vlan passthrough
   load-balancing
    pw-label
    flow-label both
   !
  !
 !
 pw-class <class-name>
  encapsulation mpls
   transport-mode ethernet
   load-balancing
    pw-label
    flow-label both
   !
  !
 !

Best wishes,
rjoensen
