### ISSUE TITLE
iosxr_mpls_ldp

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#159]
Hello,

mpls ldp, unable to configure gip sync delays

address family, unable to configure label, local, allocate.

Maybe I am reading the documentation wrong, but I see no references for these.

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/fa1da3bef3745edc28a7cedd002e66b272611952

**Comment by danischm** [comment]
Addressed in v0.2.4 .
