### ISSUE TITLE
iosxr_l2vpn - ref #158

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#170]
Hello,

In reference to issue #158

I just got around to actually test this and it appears I was not very clear when reporting this. I believe what's missing is jut the pw-class ability.

l2vpn
load-balancing flow src-dst-ip
pw-class <class-name>
encapsulation mpls
transport-mode vlan passthrough
load-balancing
pw-label
flow-label both
!
!
!
pw-class <class-name>
encapsulation mpls
transport-mode ethernet
load-balancing
pw-label
flow-label both
!
!
!

Best wishes,
rjoensen

**Comment by danischm** [comment]
Isn't this covered with this resource? https://registry.terraform.io/providers/CiscoDevNet/iosxr/latest/docs/resources/l2vpn_pw_class

**Comment by rjoensen** [comment]
Hello,

Yes it does. Confirmed it works. Thank you!
