### ISSUE TITLE
ioxr_interface mtu over 9000

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#171]
Hello,

There seems to be an issue to configure MTU value higher than 9000. The documentation specifies that you can go way higher than that, but if I configure it at 9000, no problems, 9001, and it errors out.

From the CLI, I can set it higher with no issues. 

The error message is also not very descriptive, it complains about other resources that are used too.

  # iosxr_interface.L2VPN will be updated in-place
  ~ resource "iosxr_interface" "L2VPN" {
        id             = "Cisco-IOS-XR-um-interface-cfg:/interfaces/interface[interface-name=TwentyFiveGigE0/0/0/11]"
      ~ mtu            = 9000 -> 9118
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Error: Client Error
│ 
│   with iosxr_flow_sampler_map.ONE-OF-ONE,
│   on sampler.tf line 1, in resource "iosxr_flow_sampler_map" "ONE-OF-ONE":
│    1: resource "iosxr_flow_sampler_map" "ONE-OF-ONE" {
│ 
│ Get request failed, got error: rpc error: code = Unavailable desc = error reading from server: read tcp <snipped>:58259-><snipped>:57400: use of closed network connection

Not sure how to handle this.

Best wishes,
rjoensen

**Comment by danischm** [comment]
Is that the same interface being used for gRPC connectivity?

**Comment by rjoensen** [comment]
gRPC is via one of the mgmt interfaces, so no.

**Comment by danischm** [comment]
I cannot recreate this issue. Can you maybe try to come up with a minimal config to recreate the issue?

**Comment by danischm** [comment]
Excellent, thanks for confirmation!
