### ISSUE TITLE
Add OSPF auto-cost

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#174]
Please add the ability to configure OSPF auto-cost

https://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r3-7/routing/command/reference/rr37ospf.html#wp998898

Thanks

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/1bea699db5d8f7dfd921485bb0ab284652dd4235

**Comment by danischm** [comment]
Added in v0.2.6 release.
