### ISSUE TITLE
iosxr_interface missing pieces

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#175]
Hello,

I am not finding this in the documentation, so I apologize if this already exists however I seem to be able to configure the following:

 ipv4 verify unicast source reachable-via any
 ipv6 nd suppress-ra
 ipv6 verify unicast source reachable-via any
 ipv4 access-group <access-list> ingress hardware-count

Would appreciate if this can be added or if you can direct me to the right thing.

Best wishes,
rjoensen

**Comment by rjoensen** [comment]
Also, closed issue #171 doesn't seem to be fixed 100%.

I can apply this:
Hello,

Well, this issue persists again. 

resource "iosxr_interface" "MONITOR" {
  interface_name = "TwentyFiveGigE0/0/0/11"
  description = "MONITOR"
  mtu = 9118
  flow_ipv4_ingress_monitor_samplers = [
    {
      monitor_map_name = "MAP"
      sampler_map_name = "SAMPLER"
    }
  ]
  flow_ipv6_ingress_monitor_samplers = [
    {
      monitor_map_name = "MAP"
      sampler_map_name = "SAMPLER"
    }
  ]
}

But once applied, if I run it terraform apply again, it errors out, but it has configured it. I need to remove this entire thing from the config to make terraform apply work again.

Its acting pretty strange.

Best wishes,
rjoensen

**Comment by danischm** [comment]
What version of XR are you running? Unfortunately, I cannot test this easily as netflow is not supported on XRv.

**Comment by rjoensen** [comment]
Hello,

We are using 7.8.2, however, I have found the issue causing problems. Running terraform fmt on the entire directory has made the problems go away in terms of causing issues with MTU and having samplers configured.

We are still lacking the ability to add ACL to an interface like I described in the first post in this thread.

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/27b6ccff1e0d83bfc7eee884529a5f82304eabe8

**Comment by danischm** [comment]
Added in v0.3.0 release.

**Comment by rjoensen** [comment]
Tested and confirm.
