### ISSUE TITLE
Add route-reflector client for BGP

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#184]
When configuring the resources "iosxr_router_bgp_neighbor_address_family"  or "iosxr_router_bgp_neighbor_group", there is no option to enable the neighbors address family as a route-reflector client.

Here are two docs to support:
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-3/routing/configuration/guide/b-routing-cg-asr9000-73x/implementing-BGP.html#task_1213209

https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-3/routing/configuration/guide/b-routing-cg-asr9000-73x/implementing-BGP.html#task_1213997

Thanks

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/54d1cba18122a79ddf1ab9ab9966d3a23f232644

**Comment by danischm** [comment]
Added in v0.2.6 release.
