### ISSUE TITLE
iosxr_logging

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#188]
Hello

In iosxr_logging, there does not seem to be the ability to configure a port.

E.g. port default or port <custom>.

Example:
logging console disable
logging <snipped> vrf <snipped> severity info port <snipped>
logging <snipped> vrf <snipped> severity info port default
logging source-interface Loopback0
logging hostnameprefix <snipped>

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/833ce1c1050dc44e68fa3aaa259e2254bf864cff

**Comment by danischm** [comment]
You need to use the `iosxr_logging_vrf` resource even if it is the `default` vrf.

**Comment by danischm** [comment]
Added in v0.2.6 release.

**Comment by rjoensen** [comment]
Tested and confirmed.
