### ISSUE TITLE
iosxr_router_bgp - Remove requirement for EBGP Multihop

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#190]
Is it possible to remove EBGP multi hop as required?

It gives the error below if I'm running iBGP neighbor

╷
│ Error: Client Error
│ 
│   with iosxr_router_bgp.router_bgp["pe04"],
│   on iosxr_300_bgp_config.tf line 1, in resource "iosxr_router_bgp" "router_bgp":
│    1: resource "iosxr_router_bgp" "router_bgp" {
│ 
│ Set request failed, got error: rpc error: code = Internal desc = gNMI commit-request: operation-failed: Change would result in internal neighbor (10.31.1.11) with external-only config:
│ Cisco-IOS-XR-um-router-bgp-cfg:router/bgp/as[as-number = '65331']/neighbors/neighbor[neighbor-address = '10.31.1.11']/ebgp-multihop/maximum-hop-count

Same error if I run the config directly on the router

router bgp 65331
 neighbor 10.31.1.11
  ebgp-multihop 5
!!% Change would result in internal neighbor (10.31.1.11) with external-only config
 !
!

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/e46e707778f9a6b9616230e99270249676bad9a8

**Comment by danischm** [comment]
Added in v0.3.1 release.
