### ISSUE TITLE
related to #189

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#191]
Hello,

This relates to #189 

You can now assign an access list to communities and to v3 groups, but you cannot assign this to specific snmp-server user definitions. I think groups is good enough, but a lot of businesses assign it to the user portion.

Example:
snmp-server user <user> <group> v3 auth sha encrypted <snipped> priv aes 128 encrypted <snipped> IPv4 <ACL> SystemOwner

Best wishes,
rjoensen

**Comment by rjoensen** [comment]
The example should look like this:
snmp-server user "user" "group" v3 auth sha encrypted "snipped" priv aes 128 encrypted "snipped" IPv4 "ACL" SystemOwner

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by rjoensen** [comment]
Thank you! Appreciate all of the work you have done on this provider!

Best wishes,
rjoensen

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/4808d5fc1dd5b6d9f9102129603043f41ba3b36b

**Comment by danischm** [comment]
Added in v0.3.2 release.
