### ISSUE TITLE
Add segment routing config for OSPF

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#192]
Hi,

Could you please add the support for Segment routing config using OSPF?

Steps to enable on OSPF process:
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-6/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-76x/configure-sr-for-ospf-protocol.html#task_4D379C0F92814C319A7D5C567C87DF2A
1- configure
2- router ospf process-name
3- segment-routing mpls
4- segment-routing sr-prefer
5- area area
6- segment-routing mpls
7- exit
8- Use the commit or end command.

Commands to configure loopback with prefix SID
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r7-6/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-76x/configure-sr-for-ospf-protocol.html#task_1E8B0B8FBA20429DA670496C27EE8389
1- configure
2- router ospf process-name
3- area value
4- interface Loopback interface-instance
5- prefix-sid [strict-spf| algorithm algorithm-number] {index SID-index | absolute SID-value } [n-flag-clear] [explicit-null]
6- Use the commit or end command.

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/4808d5fc1dd5b6d9f9102129603043f41ba3b36b

**Comment by danischm** [comment]
Added in v0.3.2 release.
