### ISSUE TITLE
Add fast-reroute tilfa for OSPF

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#193]
Hi,

Could you please add Fast-Reroute TILFA for OSPF?
https://www.cisco.com/c/en/us/td/docs/routers/asr9000/software/asr9k-r6-3/segment-routing/configuration/guide/b-segment-routing-cg-asr9000-63x/b-segment-routing-cg-asr9000-63x_chapter_01001.html#id_32550

SUMMARY STEPS

1- configure
2- router ospf process-name
3- area area-id
4- interface type interface-path-id
5- fast-reroute per-prefix
6- fast-reroute per-prefix ti-lfa
7- fast-reroute per-prefix tiebreaker { node-protecting | srlg-disjoint } index priority

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/4808d5fc1dd5b6d9f9102129603043f41ba3b36b

**Comment by danischm** [comment]
Added in v0.3.2 release.
