### ISSUE TITLE
Improve fast-reroute for ISIS

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#195]
When implementing the resource iosxr_router_isis_interface_address_family using fast_reroute_per_prefix_levels, the commands could be improved.

To enable TI-FLA, two commands are needed:
 fast-reroute per-prefix
 fast-reroute per-prefix ti-lfa
 
On both cases, level is optional and not required (as it's today)  

I would recommend changing the resource to be like:
- fast_reroute_per_prefix (not fast_reroute_per_prefix_levels)
- optional: level (1 or 2)

- fast_reroute_per_prefix_ti_lfa
- optional: level (1 or 2)

This is valid for both af_names/saf_names (ipv4 unicast and ipv6 unicast)

See example below:

router isis CORE
 interface GigabitEthernet0/0/0/0
  address-family ipv4 unicast
   fast-reroute per-prefix
   fast-reroute per-prefix ti-lfa
  !
 !
 interface GigabitEthernet0/0/0/1
  address-family ipv4 unicast
   fast-reroute per-prefix level 2
   fast-reroute per-prefix ti-lfa level 2
  !
 !

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/5703cbd36b9b76cf59f09349778e4b2b0665b395

**Comment by danischm** [comment]
Added in v0.3.2 release.
