### ISSUE TITLE
BGP questions/missing features

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#197]
Hello,

We’re just getting to implementing BGP into Terraform and I am a little bit confused as to what is the best practice here.

I have started to use iosxr_router_bgp, but I see there is _vrf_ for all of the resources as well. It appears that VRF has been equipped with route policies, however its not implemented in all of the _vrf_ resources either. So this is a little bit confusing.

Example:

router bgp #ASN
 timers bgp 30 90 60
 bgp router-id #snipped
 bgp bestpath compare-routerid
 address-family ipv4 unicast
  maximum-paths ibgp 2
  nexthop trigger-delay critical 0
  nexthop trigger-delay non-critical 0
  network prefix/network route-policy #POLICY
  redistribute connected route-policy #POLICY
  redistribute static route-policy #POLICY

(This is for both IPv4 and IPv6).

neighbor configuration seems to be lacking this ability as well.

Example:

neighbor #neighbor
 address-family ipv4 unicast
 route-policy #POLICY in/out

Best wishes,
rjoensen

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by rjoensen** [comment]
Thank you! Appreciate all of the work you have done on this provider!

Best wishes,
rjoensen

**Comment by summed** [comment]
Hi @danischm,

If we wanted to assist with fixing this issue, where should we start?

atb!

**Comment by danischm** [comment]
All the code and documentation is auto-generated from YANG models and definitions being maintained here (https://github.com/CiscoDevNet/terraform-provider-iosxr/tree/main/gen/definitions). To add support for additional BGP neighbor configurations you would need to add the relevant attributes here (https://github.com/CiscoDevNet/terraform-provider-iosxr/blob/main/gen/definitions/router_bgp.yaml) and then run `go generate` to generate the code, documentation and tests.

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/c4af7dfda1f4f45e968a6e5e79962c72d90da24a

**Comment by danischm** [comment]
Added in v0.3.2 release.
