### ISSUE TITLE
iosxr_router_bgp_neighbor_group

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#199]
Hello,

This is an additional for issue #197 

We'd like the ability to configure via terraform route-policy under address-family for neighbor group.

Example:
  update-source Loopback0
  address-family ipv4 unicast
   route-policy #POLICY in
   route-policy #POLICY out
   soft-reconfiguration inbound always

Best wishes,
rjoensen

**Comment by danischm** [comment]
Thanks for raising the issue. We are looking to add support for this.

**Comment by rjoensen** [comment]
Thank you! Appreciate all of the work you have done on this provider!

Best wishes,
rjoensen

**Comment by danischm** [comment]
Added in v0.3.2 release.
