### ISSUE TITLE
OSPF - Segment Routing - Prefix configuration improvement suggestion

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#214]
For the resource "iosxr_router_ospf_area_interface", the Nested schema "prefix_sid_algorithms" could be improved as follow:
- absolute_sid_label OR index_sid_index is required, not both as one excludes the need of the other
- change algorithm_number to optional

**Comment by danischm** [comment]
`algorithm_number` cannot be optional as it is the key of the list element.

**Comment by danischm** [comment]
Other attributes are optional from v0.5.0 release.
