### ISSUE TITLE
Add BGP Next-hop-self

### ISSUE THREAD

**Issue by tiagosil-cisco** [CiscoDevNet/terraform-provider-iosxr#215]
Could you please evaluate adding the flag (true or false) to BGP Next-hop-self?
https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-1/routing/configuration/guide/routing_cg41xr12k_chapter1.html#task_1207381

This can be used inside address-families for the resources below (it's optional)
- iosxr_router_bgp_neighbor_group

Example:
```
RP/0/RP0/CPU0:A-NCS5-PE01#show run router bgp 65300 neighbor-group TO_RR 
Mon Nov 27 21:22:10.065 UTC
router bgp 65300
 neighbor-group TO_RR
  remote-as 65300
  update-source Loopback0
  address-family vpnv4 unicast
   import reoriginate stitching-rt
   advertise vpnv4 unicast re-originated
   next-hop-self  <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !
  address-family vpnv6 unicast
   import reoriginate stitching-rt
   advertise vpnv6 unicast re-originated
   next-hop-self  <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !
  address-family ipv4 rt-filter
  !
  address-family l2vpn evpn
   next-hop-self  <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !

```
- iosxr_router_bgp_neighbor_address_family
Example
```
router bgp 65300
 bgp router-id 10.30.1.1
 default-information originate
 mpls activate
  interface TenGigE0/0/0/39.1300
 !
 address-family ipv4 unicast
  network 0.0.0.0/0
  network 10.0.10.0/24
  redistribute connected route-policy CONNECTED-TO-BGP-LU(1)
  allocate-label all
 !
 address-family vpnv4 unicast
 !
 address-family ipv6 unicast
 !
 address-family vpnv6 unicast
 !
 address-family ipv4 rt-filter
 !
 address-family l2vpn evpn
 !
 neighbor-group TO_RR
  remote-as 65300
  update-source Loopback0
  address-family vpnv4 unicast
   import reoriginate stitching-rt
   advertise vpnv4 unicast re-originated
   next-hop-self <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !
  address-family vpnv6 unicast
   import reoriginate stitching-rt
   advertise vpnv6 unicast re-originated
   next-hop-self <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !
  address-family ipv4 rt-filter
  !
  address-family l2vpn evpn
   next-hop-self <<<<<<<<<<<<<<<<<<<<<<<
   soft-reconfiguration inbound
  !
 !        
```

**Comment by summed** [comment]
Believe I have added it to the PR https://github.com/CiscoDevNet/terraform-provider-iosxr/pull/213 - Could you please have a look?

**Comment by tiagosil-cisco** [comment]
Sorry, I didn’t test before posting. I just looked at the documentation. It’s working using next_hop_self = true.
Thanks

From: Noname ***@***.***>
Date: Monday, November 27, 2023 at 5:36 PM
To: CiscoDevNet/terraform-provider-iosxr ***@***.***>
Cc: Tiago Lugarini Silva (tiagosil) ***@***.***>, Author ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-iosxr] Add BGP Next-hop-self (Issue #215)

Believe I have added it to the PR #213<https://github.com/CiscoDevNet/terraform-provider-iosxr/pull/213> - Could you please have a look?

**Comment by danischm** [comment]
Added in v0.5.0 release.
