### ISSUE TITLE
Resource: router hsrp

### ISSUE THREAD

**Issue by rjoensen** [CiscoDevNet/terraform-provider-iosxr#226]
Hello,

In resource iosxr_router_hsrp_interface_address_family_ipv6_group_v2 it would be nice to be able to set address_link_local_autoconfig without necessarily specifying legacy_compatability

Example,
address-family ipv6
   hsrp X
    priority X
    address global x:x:x:x::x
    address linklocal autoconfig

Also in iosxr_router_hsrp_interface_address_family_ipv4_group_v2 it would be nice to be able to set preempt, not delay, just preempt. 

Example,
  address-family ipv4
   hsrp x
    preempt
    
Best wishes,
Joensen

**Comment by rjoensen** [comment]
Hello, any chance to have an update on this?

**Comment by danischm** [comment]
The `preempt` option does not exist in the YANG model. The equivalent is:
```
preempt_delay = 0
```

**Comment by danischm** [comment]
`address_link_local_autoconfig` added in v0.5.0 release.
