### ISSUE TITLE
missing "use af-group" in rescource "iosxr_router_bgp_neighbor_group"

### ISSUE THREAD

**Issue by hani010** [CiscoDevNet/terraform-provider-iosxr#262]
Hi all, 
i miss the "use af-group" in rescource "iosxr_router_bgp_neighbor_group".
Can please you add this. :-)

 PATH:
path = "Cisco-IOS-XR-um-router-bgp-cfg:router/bgp/as[as-number=65501]/neighbor-groups/neighbor-group[neighbor-group-name=<ng_name>]/address-families/address-family[af-name=ipv4-unicast]/use"
  
Thank you and Regards

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/3e90220e4729031da72b47b8f8451a22257d756b

**Comment by danischm** [comment]
Added in 0.5.2 release.
