### ISSUE TITLE
Unable to track state of changes

### ISSUE THREAD

**Issue by andyman212** [CiscoDevNet/terraform-provider-iosxr#269]
Not sure if this is an issue or just a current limitation.

When using resources It does not track the state, everytime i run a Plan it tries to replace, such items as VRF's cause errors as they are in use.

The only way to get this to work is to use the iosxr_gnmi Resource and define each resource usign GRPC paths.

```terraform
terraform {
  required_providers {
    iosxr = {
      source = "CiscoDevNet/iosxr"
    }
  }
}

provider "iosxr" {
  host     = "address"
  username = "username"
  password = "password!"
  tls      = false
}

# This works keeping track of the TF State
resource "iosxr_gnmi" "banner_login" {
  path = "Cisco-IOS-XR-um-banner-cfg:/banners/banner[banner-type=login]"
  attributes = {
    line = "Authorized Access Only, this device is for authorized users only and is protected by law."
  }
}

# This does not work keeping track of the TF State
resource "iosxr_banner" "example" {
  banner_type = "login"
  line        = "Authorized Access Only, this device is for authorized users only and is protected by law."
}
```

Any help would be appreciated.

Andy

**Comment by andyman212** [comment]
Of course.

So on initial creation.

  # iosxr_banner.example will be created
  + resource "iosxr_banner" "example" {
      + banner_type = "login"
      + id          = (known after apply)
      + line        = "Authorized Access Only, this device is for authorized users only and is protected by law."
    }
    
    on no change when running a Plan.
    
      # iosxr_banner.example will be updated in-place
  ~ resource "iosxr_banner" "example" {
        id          = "Cisco-IOS-XR-um-banner-cfg:/banners/banner[banner-type=login]"
      + line        = "Authorized Access Only, this device is for authorized users only and is protected by law."
        # (1 unchanged attribute hidden)
    }

It sees the Line as a change and this works ok for this, but objects like VRF's it will not work as the way they cannot be deleted on IOS-XR.

Hope that makes sense. 

Thanks

**Comment by danischm** [comment]
Hmm.. it does work in my environment. Can you enable debug logs (`export TF_LOG=Trace`) and share them?

**Comment by andyman212** [comment]
Strange, I am running this again IOS-XR 9000v Version 7.4.1

**Comment by danischm** [comment]
Anything before 7.6.1 does not fully support the unified YANG models. Please try with 7.6.1+.

**Comment by andyman212** [comment]
Thanks will see If I can get it, and will try my code against the IOS-XR Sandbox in the meantime.

Appreciate all your help.

**Comment by andyman212** [comment]
I can confirm after upgrading this is now working as intended.

Thanks Again
