### ISSUE TITLE
Error on enabling next-hop-self option under resource "iosxr_router_bgp_vrf_neighbor_address_family"

### ISSUE THREAD

**Issue by tomvrugt** [CiscoDevNet/terraform-provider-iosxr#271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enabling `next_hop_self` under resource "iosxr_router_bgp_vrf_neighbor_address_family" results in the following error:

```
╷
│ Error: Client Error
│
│   with iosxr_router_bgp_vrf_neighbor_address_family.tst_vrf_tom,
│   on main.tf line 44, in resource "iosxr_router_bgp_vrf_neighbor_address_family" "tst_vrf_tom":
│   44: resource "iosxr_router_bgp_vrf_neighbor_address_family" "tst_vrf_tom" {
│
│ Set request failed, got error: rpc error: code = Internal desc = {
│  "cisco-grpc:errors": {
│   "error": [
│    {
│     "error-type": "application",
│     "error-tag": "operation-failed",
│     "error-severity": "error",
│     "error-path": "Cisco-IOS-XR-um-router-bgp-cfg:router/bgp/as[as-number = '65003']/vrfs/vrf[vrf-name = 'TST_VRF_TOM']/neighbors/neighbor[neighbor-address = '1.2.3.4']/address-families/address-family[af-name = 'ipv4-unicast']/next-hop-self",
│     "error-message": "'sysdb' detected the 'warning' condition 'A verifier or EDM callback function returned: 'not found''"
│    }
│   ]
│  }
│ }
│
╵
```
### Affected Resource(s):
- iosxr_router_bgp_vrf_neighbor_address_family
- possibly also iosxr_router_bgp_neighbor_address_family (not verified)

### IOS-XR version and Platform
IOS XRv 9000 Router running IOS XR 7.9.2

### Provider version

ciscodevnet/iosxr v0.5.2

### Output/ Error message

Find debug output attached: [next-hop-self_debug.txt](https://github.com/user-attachments/files/17958067/next-hop-self_debug.txt)

### Expected Behavior

`next-hop-self` option should be configured under `router bgp 65003 vrf TST_VRF_TOM neighbor 1.2.3.4 address-family ipv4 unicast `

### Actual Behavior

Errors with error-message: "'sysdb' detected the 'warning' condition 'A verifier or EDM callback function returned: 'not found''

### Terraform configuration to reproduce

```
terraform {
  required_providers {
    iosxr = {
      source  = "CiscoDevNet/iosxr"
      version = ">= 0.5.2"
    }
  }
}

provider "iosxr" {
  username = "***"
  password = "***"
  host     = "10.131.3.122:57777"
}

resource "iosxr_vrf" "vrf_TST_VRF_TOM" {
  vrf_name                    = "TST_VRF_TOM"
  address_family_ipv4_unicast = true
  rd_two_byte_as_as_number    = "65123"
  rd_two_byte_as_index        = 1
}

resource "iosxr_router_bgp" "router_bgp_65003" {
  as_number     = "65003"
  bgp_router_id = "22.22.22.22"
}

resource "iosxr_router_bgp_address_family" "router_bgp_65003_af_vpnv4-unicast" {
  as_number = iosxr_router_bgp.router_bgp_65003.as_number
  af_name   = "vpnv4-unicast"
}

resource "iosxr_router_bgp_address_family" "router_bgp_65003_af_ipv4-unicast" {
  as_number = iosxr_router_bgp.router_bgp_65003.as_number
  af_name   = "ipv4-unicast"
}

resource "iosxr_router_bgp_vrf" "router_bgp_vrf_TST_VRF_TOM" {
  as_number     = iosxr_router_bgp.router_bgp_65003.as_number
  vrf_name      = iosxr_vrf.vrf_TST_VRF_TOM.vrf_name
  bgp_router_id = "99.99.99.99"
  neighbors = [
    {
      neighbor_address    = "1.2.3.4"
      remote_as           = "65123"
      local_as            = "65123"
      local_as_no_prepend = true
      local_as_replace_as = true
    }
  ]
}

resource "iosxr_router_bgp_vrf_address_family" "router_bgp_vrf_TST_VRF_TOM_af_ipv4-unicast" {
  as_number = iosxr_router_bgp.router_bgp_65003.as_number
  vrf_name  = iosxr_router_bgp_vrf.router_bgp_vrf_TST_VRF_TOM.vrf_name
  af_name   = iosxr_router_bgp_address_family.router_bgp_65003_af_ipv4-unicast.af_name
}

resource "iosxr_router_bgp_vrf_neighbor_address_family" "router_bgp_vrf_TST_VRF_TOM_neighbor_af_ipv4-unicast" {
  as_number        = iosxr_router_bgp.router_bgp_65003.as_number
  vrf_name         = iosxr_router_bgp_vrf.router_bgp_vrf_TST_VRF_TOM.vrf_name
  neighbor_address = iosxr_router_bgp_vrf.router_bgp_vrf_TST_VRF_TOM.neighbors[0].neighbor_address
  af_name          = iosxr_router_bgp_address_family.router_bgp_65003_af_ipv4-unicast.af_name
  next_hop_self    = true
}
```

### Important Factoids

* Tested against IOS XR 7.11.1 : Same error there.
* Tested against IOS XR 7.6.2: Works! But we run  7.9.21 in production.

### References

* seems related to #267 
* https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/57a777099cfd9cda06267a74256dddbf438e4fd3

**Comment by danischm** [comment]
Can you check the logs on the device as well? There might be a more verbose message logged there.

**Comment by tomvrugt** [comment]
> Can you check the logs on the device as well? There might be a more verbose message logged there.

output of `show logging` on device during apply:

```
RP/0/RP0/CPU0:Nov 29 11:48:40.501 UTC: emsd[1133]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'cisco'. Use 'show configuration commit changes 1000001239' to view the changes.
RP/0/RP0/CPU0:Nov 29 11:48:41.354 UTC: emsd[1133]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'cisco'. Use 'show configuration commit changes 1000001240' to view the changes.
RP/0/RP0/CPU0:Nov 29 11:48:43.964 UTC: emsd[1133]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'cisco'. Use 'show configuration commit changes 1000001241' to view the changes.
RP/0/RP0/CPU0:Nov 29 11:48:45.160 UTC: bgp[1094]: %ROUTING-BGP-3-CONFIG_SET : Notify for default/0/65001/ord_b/TST_VRF_TOM/nbr/0x0/edm/ord_u/0x3/01020304/________/0x20/ord_s/0x0/ord_c/activate failed with error: 'BGP' detected the 'warning' condition 'Neighbor not found', system may now be in an inconsistent state.
RP/0/RP0/CPU0:Nov 29 11:48:45.160 UTC: bgp[1094]: %ROUTING-BGP-3-CONFIG_DEL : Notify delete of default/0/65001/ord_b/TST_VRF_TOM/nbr/0x0/edm/ord_u/0x3/01020304/________/0x20/ord_s/0x0/ord_c/activate failed with warning: 'BGP' detected the 'warning' condition 'Neighbor not found', no further action necessary.
```

**Comment by tomvrugt** [comment]
Any other command/logging i could check on the device?

**Comment by danischm** [comment]
You are missing the dependencies between the different resources. For example, you have to make sure the `iosxr_router_bgp_vrf_neighbor_address_family` depends on the `iosxr_router_bgp_vrf ` resource.

```terraform
resource "iosxr_router_bgp_vrf_neighbor_address_family" "tst_vrf_tom" {
  as_number        = "65003"
  vrf_name         = iosxr_router_bgp_vrf.tst_vrf_tom.vrf_name
  neighbor_address = "1.2.3.4"
  af_name          = "ipv4-unicast"
  next_hop_self    = true
}
```

**Comment by tomvrugt** [comment]
> You are missing the dependencies between the different resources. For example, you have to make sure the `iosxr_router_bgp_vrf_neighbor_address_family` depends on the `iosxr_router_bgp_vrf ` resource.
> 
> ```hcl
> resource "iosxr_router_bgp_vrf_neighbor_address_family" "tst_vrf_tom" {
>   as_number        = "65003"
>   vrf_name         = iosxr_router_bgp_vrf.tst_vrf_tom.vrf_name
>   neighbor_address = "1.2.3.4"
>   af_name          = "ipv4-unicast"
>   next_hop_self    = true
> }
> ```

I updated the config in the original post to include the dependencies (did i miss any?), but still ge the same error message.

**Comment by tomvrugt** [comment]
By the way, I tested the exact same config against IOS XR 7.6.2 which applies it correctly and without errors.
Also tested against IOS XR 7.11.1 which does fail with the same error.

We are runnnig 7.9.21 on our production ASR9K (physical device), and we aim to use the IOS XRv 9000 7.9.2 as a representative staging environment.

**Comment by danischm** [comment]
This is weird. I could recreate the issue on 7.9.2. When I configured `next_hop_self` manually it was not present in the modelled config either. Could you share the output of `show run router bgp | json unified` after configuring "next-hop-self" via CLI on the XR versions you are running?

**Comment by tomvrugt** [comment]
> This is weird. I could recreate the issue on 7.9.2. When I configured `next_hop_self` manually it was not present in the modelled config either. Could you share the output of `show run router bgp | json unified` after configuring "next-hop-self" via CLI on the XR versions you are running?

Hmm interesting.....

```
RP/0/RP0/CPU0:ios#conf t
Fri Nov 29 13:43:16.465 UTC
RP/0/RP0/CPU0:ios(config)#router bgp 65003 vrf TST_VRF_TOM neighbor 1.2.3.4 address-family ipv4 unicast next-hop-self
RP/0/RP0/CPU0:ios(config)#commit

RP/0/RP0/CPU0:ios#show run router bgp | json unified
Fri Nov 29 13:44:15.224 UTC
{
 "data": {
  "Cisco-IOS-XR-um-router-bgp-cfg:router": {
   "bgp": {
    "as": [
     {
      "as-number": 65003,
      "bgp": {
       "router-id": "22.22.22.22"
      },
      "address-families": {
       "address-family": [
        {
         "af-name": "ipv4-unicast"
        },
        {
         "af-name": "vpnv4-unicast"
        }
       ]
      },
      "vrfs": {
       "vrf": [
        {
         "vrf-name": "TST_VRF_TOM",
         "bgp": {
          "router-id": "99.99.99.99"
         },
         "address-families": {
          "address-family": [
           {
            "af-name": "ipv4-unicast"
           }
          ]
         },
         "neighbors": {
          "neighbor": [
           {
            "neighbor-address": "1.2.3.4",
            "remote-as": 65123,
            "local-as": {
             "as-number": 65123,
             "no-prepend": {
              "replace-as": {

              }
             }
            },
            "address-families": {
             "address-family": [
              {
               "af-name": "ipv4-unicast"
              }
             ]
            }
           }
          ]
         }
        }
       ]
      }
     }
    ]
   }
  }
 }
}
RP/0/RP0/CPU0:ios#sh run router bgp 65003
Fri Nov 29 13:45:10.508 UTC
router bgp 65003
 bgp router-id 22.22.22.22
 address-family ipv4 unicast
 !
 address-family vpnv4 unicast
 !
 vrf TST_VRF_TOM
  bgp router-id 99.99.99.99
  address-family ipv4 unicast
  !
  neighbor 1.2.3.4
   remote-as 65123
   local-as 65123 no-prepend replace-as
   address-family ipv4 unicast
    next-hop-self
   !
  !
 !
!
```

**Comment by danischm** [comment]
Looks like an XR issue.. probably best to open a case.

**Comment by tomvrugt** [comment]
> Looks like an XR issue.. probably best to open a case.

Thanks for the quick response Daniel! I will open a TAC case then.

**Comment by tomvrugt** [comment]
For you reference, I opened TAC case 698362235

**Comment by danischm** [comment]
Maybe add a note mentioning the same config is working on 7.6.1.

**Comment by tomvrugt** [comment]
> Maybe add a note mentioning the same config is working on 7.6.1.

Good point, added it to the case.

**Comment by tomvrugt** [comment]
Closing the TAC case 698362235 due to lack of progress. We have discovered this is resolved by upgrading ASR to latest recommended release IOS-XR 24.2.2, although it introduces two new issues:
* 4-byes ASN issue #272.
* aggregate-address cannot be configured via terraform/YANG Cisco-IOS-XR-um-router-bgp-cfg on IOS-XR 24.2.2, for which I opened another TAC case 698427260
