### ISSUE TITLE
Dotted decimal AS number notation breaks BGP neighbors on IOS-XR 24.2.2

### ISSUE THREAD

**Issue by shebang42** [CiscoDevNet/terraform-provider-iosxr#272]
## Summary

BGP neighbor configuration fails when using dotted decimal AS numbers (e.g., 65002.100) in IOS-XR 24.2.2. The issue causes type inconsistencies between string and integer representations of AS numbers, leading to continuous Terraform plan differences and failed applies.

## Issue Description

When using dotted decimal AS number notation (e.g., "65002.100") for BGP neighbors in IOS-XR 24.2.2, there is a discrepancy in how the remote AS numbers are handled, causing BGP neighbor configuration issues.

## Symptoms

1. During Terraform plan/apply operations, the provider continuously shows differences for AS numbers in dotted decimal notation:

```hcl
# module.asr.module.router_bgp.iosxr_router_bgp_vrf.from_yaml["AMS-ANC01"] will be updated in-place
  ~ resource "iosxr_router_bgp_vrf" "from_yaml" {
      ~ neighbors = [
          ~ {
              ~ local_as  = "\"1234567890\"" -> "1234567890"
              ~ remote_as = "\"1234567890\"" -> "1234567890"
              # (7 unchanged attributes hidden)
            }
        ]
    }
```

2. Test failures are observed when validating BGP VRF configurations:
```
go test -v -failfast -fullpath ./... -run RouterBGPVRF
<..>
TestAccDataSourceIosxrRouterBGPVRF: Check failed: 
data.iosxr_router_bgp_vrf.test: Attribute 'neighbors.0.remote_as' expected "65002.100", got "\"65002.100\""
```

### IOS-XR Version
- 24.2.2

#### IOS-XR 7.9.2 Output
```
RP/0/RP0/CPU0:xr9kv-dc1#sh run router bgp | json unified-model
```

```json
{
 "data": {
  "Cisco-IOS-XR-um-router-bgp-cfg:router": {
   "bgp": {
    "as": [
     {
      "as-number": 65001,
      "neighbors": {
       "neighbor": [
        {
         "neighbor-address": "1.2.3.4",
         "remote-as": 65002
        },
        {
         "neighbor-address": "10.2.3.4",
         "remote-as": 6500310    <--------------------------------------------
        }
       ]
      }
     }
    ]
   }
  }
 }
}
```

#### IOS-XR 24.2.2 Output (showing inconsistency)
```
RP/0/RP0/CPU0:xr9kv-dc1#sh run router bgp | json unified-model
```

```json
{
 "data": {
  "Cisco-IOS-XR-um-router-bgp-cfg:router": {
   "bgp": {
    "as": [
     {
      "as-number": 65001,
      "neighbors": {
       "neighbor": [
        {
         "neighbor-address": "1.2.3.4",
         "remote-as": 65002
        },
        {
         "neighbor-address": "10.2.3.4",
         "remote-as": "6500310"     <--------------------------------------------
        }
       ]
      }
     }
    ]
   }
  }
 }
}
```

## Related Issues/PRs
- https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/d1282fe70b6be203cfb8b05712993e9392813142
- https://github.com/CiscoDevNet/terraform-provider-iosxr/issues/263

## Impact
- Continuous drift detection in Terraform plans
- Failed Terraform applies
- Potential BGP neighbor establishment issues

## Expected Behavior
Remote AS numbers should be consistently handled as integers in the JSON output, regardless of whether they are input in dotted decimal or plain notation.

## Workaround
Remove the `read_raw` from AS or revert commit d1282fe

## Version Matrix
| IOS-XR Version | Status |
|----------------|---------|
| 7.9.2 | Working ✅ |
| 24.2.2 | Broken ❌ |

**Comment by tomvrugt** [comment]
Removing 

`read_raw: true`

https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/d1282fe70b6be203cfb8b05712993e9392813142#diff-25e4bbf6b5931dd8c22b620695a4e189f290cccb733e6ffcfefd1d958f9ae58dR83

Does fix _this_ issue, but would reintroduce the issue described in #263

@danischm can you advise how to fix this?

**Comment by tomvrugt** [comment]
@danischm Looking at your comment in https://github.com/CiscoDevNet/terraform-provider-iosxr/issues/263#issuecomment-2413357287 I guess the time has come to revert the temporary workaround on the provider side since, in the meantime, this has been fixed on the XR YANG/gNMI side of things (in the current Cisco recommended release 24.2.2). Therefore `read_raw: true` should be removed again fixing this issue. Agree?

**Comment by danischm** [comment]
Reverted the workaround: https://github.com/CiscoDevNet/terraform-provider-iosxr/commit/b8ea0497df6ad33a8af28682a9ca25e1bea63bba

**Comment by shebang42** [comment]
Thanks for the fix in b8ea049.  This solves our issue!

While this resolves the AS number handling for newer IOS-XR versions, I'd like to propose adding version-aware data handling to maintain compatibility across IOS-XR releases.
A generic version handler in the client could help manage differences between IOS-XR versions without requiring version-specific code paths throughout the codebase. This would make the provider more robust for users running different IOS-XR versions.

**Comment by edudppaz** [comment]
@danischm  this revert of workaround basically breaks the asn mapping on all other OS versions previous to 24.2.2.

**Comment by danischm** [comment]
As mentioned in the other thread, it is a bug on the XR side, which has now been fixed. Once a bug has been fixed in a recommended release, I would prefer to stay away from version specific implementations as this becomes hard to maintain going forward. If you rely on that particular feature, you can still use v0.5.2 of the provider until you have upgraded to a fixed release or request a backport of the fix to another release train. Having said that, I am open for PRs and updates to the code generator to handle such discrepancies.
